node {
    docker.withRegistry('https://hub.docker.com/', 'docker-hub-credentials') {
    	def mvnHome
    	
    	stage('checkout'){
        
        mvnHome = tool 'M3'
        git url: 'https://github.com/ansumanverma/workspace.git'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
        }
    
    dir('testnewproject'){
      
    	
    	stage('create deployment'){
    	    sh 'kubectl delete deployments testnewprojectapi || true' 
	    sh 'kubectl create -f deployment.yaml --validate=false'
    	}
    	
    	stage('create service'){
	    sh 'kubectl delete services testnewprojectapiservice || true'
	    sh 'kubectl create -f services.yaml --validate=false'
    	}
    }
    }
}
